-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.NAME
FROM (
    SELECT I.ANIMAL_ID,
           I.NAME,
           (O.DATETIME - I.DATETIME) AS DATETIME
    FROM ANIMAL_INS I
    JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
    ORDER BY DATETIME DESC
) A
WHERE ROWNUM <= 2;
